// frontend/src/components/ui/spinner.tsx
import { cn } from "@/lib/utils"
import { HugeiconsIcon } from "@hugeicons/react"
import { Loading03Icon } from "@hugeicons/core-free-icons"

function Spinner({ className }: React.ComponentProps<"svg">) {
  return (
    <HugeiconsIcon icon={Loading03Icon} strokeWidth={2} role="status" aria-label="Loading" className={cn("size-4 animate-spin", className)} size={16} />
  )
}

export { Spinner }

// frontend-nuxt/app/components/ui/Spinner.vue
<script setup lang="ts">
import { Loading03Icon } from '@hugeicons/core-free-icons'
import { cn } from '@/lib/utils'

const props = defineProps<{ class?: string }>()
</script>

<template>
  <HugeIcon
    :icon="Loading03Icon"
    :stroke-width="2"
    :size="16"
    role="status"
    aria-label="Loading"
    :class="cn('size-4 animate-spin', props.class)"
  />
</template>
