// frontend/src/components/ExistingPatientReview.tsx
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { HugeiconsIcon } from '@hugeicons/react';
import { Mail01Icon, CallIcon, Clock01Icon, Appointment01Icon, ArrowRight02Icon, Time02Icon, Cancel01Icon } from '@hugeicons/core-free-icons';
import { CancelAppointmentDialog } from '@/components/cancel-appointment-dialog';
import { Spinner } from '@/components/ui/spinner';

export interface ExistingPatientData {
  id: string;
  first_name: string;
  last_name: string;
  phone: string;
  email: string;
}

export interface LastDoctorData {
  doctor_id: string;
  doctor_name: string;
  specialization: string;
  last_appointment_date: string;
  last_appointment_time: string;
}

export interface UpcomingAppointmentData {
  id: string;
  doctor_id: string;
  doctor_name: string;
  specialization: string;
  slot_date: string;
  start_time: string;
  status: string;
}

interface ExistingPatientReviewProps {
  patient: ExistingPatientData;
  lastDoctor: LastDoctorData | null;
  doctorCount: number;
  upcomingAppointments: UpcomingAppointmentData[];
  upcomingLoading?: boolean;
  onRebookWithLastDoctor: (doctorId: string, doctorName: string) => void;
  onChangeDoctor: () => void;
  onRescheduleTime: (appointment: UpcomingAppointmentData) => void;
  onRescheduleDoctor: (appointment: UpcomingAppointmentData) => void;
  onCancelAppointment: (appointmentId: string) => Promise<void>;
}

function getInitials(first: string, last: string): string {
  return `${first.charAt(0)}${last.charAt(0)}`.toUpperCase();
}

function AppointmentCard({
  appointment,
  onRescheduleTime,
  onRescheduleDoctor,
  onCancel,
  cancelling,
}: {
  appointment: UpcomingAppointmentData;
  onRescheduleTime: () => void;
  onRescheduleDoctor: () => void;
  onCancel: () => void;
  cancelling: boolean;
}) {
  return (
    <div className="rounded-xl bg-white shadow-sm shadow-black/[0.03] border p-4 space-y-2.5">
      <div className="space-y-0.5">
        <div className="flex items-center justify-between gap-2">
          <p className="text-sm font-semibold text-foreground">Dr. {appointment.doctor_name}</p>
          <Badge variant="outline" className="text-[10px] font-normal">{appointment.specialization}</Badge>
        </div>
        <p className="text-xs text-muted-foreground">
          {appointment.slot_date} &middot; {appointment.start_time?.slice(0, 5)}
        </p>
      </div>
      <div className="flex items-center gap-3 pt-2 border-t border-foreground/5">
            <button
              type="button"
              onClick={onRescheduleTime}
              className="text-xs font-medium text-primary underline-offset-2 hover:underline transition-colors"
            >
              Reschedule
            </button>
            <span className="text-[10px] text-muted-foreground/40">&middot;</span>
            <button
              type="button"
              onClick={onRescheduleDoctor}
              className="text-xs font-medium text-primary underline-offset-2 hover:underline transition-colors"
            >
              Change doctor
            </button>
            <span className="text-[10px] text-muted-foreground/40">&middot;</span>
            <button
              type="button"
              onClick={onCancel}
              disabled={cancelling}
              className="text-xs font-medium text-destructive underline-offset-2 hover:underline transition-colors disabled:opacity-40"
            >
              {cancelling ? 'Cancelling...' : 'Cancel'}
            </button>
          </div>
        </div>
    );
}

function UpcomingAppointmentsModal({
  appointments,
  onClose,
  onRescheduleTime,
  onRescheduleDoctor,
  onCancelAppointment,
}: {
  appointments: UpcomingAppointmentData[];
  onClose: () => void;
  onRescheduleTime: (appt: UpcomingAppointmentData) => void;
  onRescheduleDoctor: (appt: UpcomingAppointmentData) => void;
  onCancelAppointment: (appointmentId: string) => Promise<void>;
}) {
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const [pendingCancelId, setPendingCancelId] = useState<string | null>(null);

  useEffect(() => {
    if (appointments.length === 0) onClose();
  }, [appointments.length, onClose]);

  const [isCancelling, setIsCancelling] = useState(false);

  const cancellingAppt = appointments.find((a) => a.id === pendingCancelId) ?? null;

  const confirmCancel = async () => {
    if (!pendingCancelId) return;
    const id = pendingCancelId;
    setPendingCancelId(null);
    setIsCancelling(true);
    setCancellingId(id);
    try {
      await onCancelAppointment(id);
    } finally {
      setCancellingId(null);
      setIsCancelling(false);
    }
  };

  return (
    <>
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.15 }}
      className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/40 p-0 sm:p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ y: 60, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        exit={{ y: 60, opacity: 0 }}
        transition={{ duration: 0.2, ease: 'easeOut' }}
        className="relative w-full max-h-[85vh] bg-white rounded-t-2xl sm:rounded-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="sticky top-0 z-10 flex items-center justify-between bg-white px-5 pt-4 pb-3 border-b border-foreground/5">
          <p className="text-sm font-semibold text-foreground">
            All upcoming appointments ({appointments.length})
          </p>
          <button
            type="button"
            onClick={onClose}
            className="size-7 flex items-center justify-center rounded-full hover:bg-muted/60 transition-colors"
          >
            <HugeiconsIcon icon={Cancel01Icon} strokeWidth={2} className="size-4 text-muted-foreground" />
          </button>
        </div>

        <div className="overflow-y-auto p-5 space-y-3">
          {appointments.map((appt) => (
            <AppointmentCard
              key={appt.id}
              appointment={appt}
              onRescheduleTime={() => onRescheduleTime(appt)}
              onRescheduleDoctor={() => onRescheduleDoctor(appt)}
              onCancel={() => setPendingCancelId(appt.id)}
              cancelling={cancellingId === appt.id}
            />
          ))}
          
        </div>
      </motion.div>
    </motion.div>

    <CancelAppointmentDialog
      open={pendingCancelId !== null}
      onOpenChange={(open) => { if (!open) setPendingCancelId(null); }}
      appointment={cancellingAppt}
      onConfirm={confirmCancel}
      isCancelling={isCancelling}
    />
  </>
  );
}

export function ExistingPatientReview({
  patient,
  lastDoctor,
  doctorCount,
  upcomingAppointments,
  upcomingLoading = false,
  onRebookWithLastDoctor,
  onChangeDoctor,
  onRescheduleTime,
  onRescheduleDoctor,
  onCancelAppointment,
}: ExistingPatientReviewProps) {
  const [cancellingId, setCancellingId] = useState<string | null>(null);
  const [pendingCancelId, setPendingCancelId] = useState<string | null>(null);
  const [isCancelling, setIsCancelling] = useState(false);
  const [showAllModal, setShowAllModal] = useState(false);

  const cancellingAppt = upcomingAppointments.find((a) => a.id === pendingCancelId) ?? null;

  const confirmCancel = async () => {
    if (!pendingCancelId) return;
    const id = pendingCancelId;
    setPendingCancelId(null);
    setIsCancelling(true);
    setCancellingId(id);
    try {
      await onCancelAppointment(id);
    } finally {
      setCancellingId(null);
      setIsCancelling(false);
    }
  };

  const soonest = upcomingAppointments.length > 0 ? upcomingAppointments[0] : null;
  const restCount = upcomingAppointments.length - 1;
  const rebookDoctor = soonest ?? lastDoctor;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: 'easeOut' }}
    >
      <Card className="w-full mx-auto bg-transparent ring-0 shadow-none overflow-visible">
        <CardHeader className="px-0">
          <CardTitle className="text-xl text-foreground">Welcome back, {patient.first_name}</CardTitle>
          <CardDescription>Great to see you again — here's your information</CardDescription>
        </CardHeader>
        <CardContent className="px-0 space-y-5">
          <Card className="overflow-hidden shadow-sm shadow-black/[0.03] border pt-0">
            <div className="h-24 bg-gradient-to-br from-amber-50 via-rose-50/60 to-primary/5" />
            <CardContent className="relative pb-0">
              <div className="flex flex-row items-start gap-5">
                <Avatar className="border-4 border-[#ffffff] shadow-lg -mt-12 size-28">
                  <AvatarFallback className="bg-slate-300 text-xl font-semibold text-slate-900">
                    {getInitials(patient.first_name, patient.last_name)}
                  </AvatarFallback>
                </Avatar>
                <div className="flex-1 pb-1">
                  <div className="flex items-center gap-2">
                    <h3 className="text-lg font-semibold leading-tight">{patient.first_name} {patient.last_name}</h3>
                    <Badge variant="secondary" className="text-[10px] px-2 py-0.5">Returning</Badge>
                  </div>
                  <div className="space-y-0.5 pt-1 text-sm text-muted-foreground">
                    <div className="flex items-center gap-3">
                      <HugeiconsIcon icon={Mail01Icon} strokeWidth={2} className="size-4 shrink-0" />
                      <span>{patient.email}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <HugeiconsIcon icon={CallIcon} strokeWidth={2} className="size-4 shrink-0" />
                      <span>{patient.phone}</span>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
            {lastDoctor && (
              <>
                <Separator />
                <CardContent className="pt-5 space-y-3">
                  <div className="flex items-center gap-2">
                    <HugeiconsIcon icon={Appointment01Icon} strokeWidth={2} className="size-4 text-primary shrink-0" />
                    <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Last visit</span>
                  </div>
                  <div className="flex items-center justify-between gap-3">
                    <div className="space-y-0.5">
                      <p className="text-sm font-semibold text-foreground">Dr. {lastDoctor.doctor_name}</p>
                      <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                        <HugeiconsIcon icon={Clock01Icon} strokeWidth={2} className="size-3.5 shrink-0" />
                        <span>{lastDoctor.last_appointment_date} &middot; {lastDoctor.last_appointment_time?.slice(0,5)}</span>
                      </div>
                    </div>
                    <Badge variant="outline" className="text-[10px] font-normal">{lastDoctor.specialization}</Badge>
                  </div>
                </CardContent>
              </>
            )}
          </Card>

          <div className="mt-6">
            <div className="space-y-3">
              {upcomingAppointments.length > 0 && (
                <div className="flex items-center justify-between gap-4 min-h-5 mt-2">
                
                  <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                    <HugeiconsIcon icon={Time02Icon} strokeWidth={2} className="size-3.5 text-primary shrink-0" />
                    Upcoming appointments
                    <span className="text-[10px] font-medium text-primary bg-primary/10 px-1.5 py-0.5 rounded-full">{upcomingAppointments.length}</span>
                  </p>
                
                {restCount > 0 && (
                  <button
                    type="button"
                    onClick={() => setShowAllModal(true)}
                    className="text-xs font-medium text-primary underline-offset-2 hover:underline transition-colors shrink-0 ml-auto"
                  >
                    View all ({upcomingAppointments.length})
                  </button>
                )}
              </div>
              )}
              {upcomingLoading ? (
                <div className="flex items-center justify-center gap-2.5 py-5">
                  <Spinner />
                  <span className="text-xs text-muted-foreground">Loading appointments...</span>
                </div>
              ) : (
                <>
                  <AnimatePresence>
                    {soonest && (
                      <motion.div
                        key={soonest.id}
                        initial={{ opacity: 0, y: -8 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, height: 0, marginBottom: 0, overflow: 'hidden' }}
                        transition={{ duration: 0.2 }}
                      >
                        <AppointmentCard
                          appointment={soonest}
                          onRescheduleTime={() => onRescheduleTime(soonest)}
                          onRescheduleDoctor={() => onRescheduleDoctor(soonest)}
                          onCancel={() => setPendingCancelId(soonest.id)}
                          cancelling={cancellingId === soonest.id}
                        />
                      </motion.div>
                    )}
                  </AnimatePresence>

                  {upcomingAppointments.length === 0 && (
                    <div className="flex flex-col items-center gap-2 rounded-xl bg-white border-2 border-dashed border-foreground/10 py-10 px-4">
                      <HugeiconsIcon icon={Appointment01Icon} strokeWidth={2} className="size-6 text-muted-foreground/40 shrink-0" />
                      <p className="text-xs text-muted-foreground">No upcoming appointments</p>
                    </div>
                  )}
                </>
              )}
            </div>
          </div>

          {!upcomingLoading && rebookDoctor && (
            <div className="flex flex-col gap-3">
              <Button className="w-full h-11 text-base gap-2 shadow-xs" onClick={() => onRebookWithLastDoctor(rebookDoctor.doctor_id, rebookDoctor.doctor_name)}>
                Rebook with Dr. {rebookDoctor.doctor_name}
                <HugeiconsIcon icon={ArrowRight02Icon} strokeWidth={2} className="size-4" />
              </Button>
              <Button variant="outline" className="w-full h-11 text-base bg-white" onClick={onChangeDoctor}>
                Choose a different doctor
              </Button>
            </div>
          )}

          {!upcomingLoading && !rebookDoctor && upcomingAppointments.length === 0 && (
            <Button className="w-full h-11 text-base gap-2 shadow-xs" onClick={onChangeDoctor}>
              {doctorCount > 1 ? 'Book an appointment' : 'Continue'}
              <HugeiconsIcon icon={ArrowRight02Icon} strokeWidth={2} className="size-4" />
            </Button>
          )}
        </CardContent>
      </Card>

      <AnimatePresence>
        {showAllModal && (
          <UpcomingAppointmentsModal
            appointments={upcomingAppointments}
            onClose={() => setShowAllModal(false)}
            onRescheduleTime={onRescheduleTime}
            onRescheduleDoctor={onRescheduleDoctor}
            onCancelAppointment={onCancelAppointment}
          />
        )}
      </AnimatePresence>

      <CancelAppointmentDialog
        open={pendingCancelId !== null}
        onOpenChange={(open) => { if (!open) setPendingCancelId(null); }}
        appointment={cancellingAppt}
        onConfirm={confirmCancel}
        isCancelling={isCancelling}
      />
    </motion.div>
  );
}

// frontend-nuxt/app/components/ExistingPatientReview.vue
<script setup lang="ts">
import { motion } from 'motion-v'
import {
  Mail01Icon,
  CallIcon,
  Clock01Icon,
  Appointment01Icon,
  ArrowRight02Icon,
  Time02Icon,
  Edit01Icon,
} from '@hugeicons/core-free-icons'
import type { Patient, LastDoctorInfo, UpcomingAppointment, AppointmentHistoryItem } from '@/lib/api'

const props = defineProps<{
  patient: Patient
  lastDoctor: LastDoctorInfo | null
  doctorCount: number
  upcomingAppointments: UpcomingAppointment[]
  upcomingLoading?: boolean
  upcomingError?: string
}>()

const emit = defineEmits<{
  retryUpcoming: []
  rebookWithLastDoctor: [doctorId: string, doctorName: string]
  changeDoctor: []
  rescheduleTime: [appt: UpcomingAppointment]
  rescheduleDoctor: [appt: UpcomingAppointment]
  cancelAppointment: [appointmentId: string, reason?: string]
  patientUpdated: [patient: Patient]
}>()

const auth = useAuthStore()
const api = useApi()

const cancellingId = ref<string | null>(null)
const pendingCancelId = ref<string | null>(null)
const isCancelling = ref(false)
const showAllModal = ref(false)
const showEditModal = ref(false)
const history = ref<AppointmentHistoryItem[]>([])
const historyLoading = ref(false)
const historyError = ref('')
const showHistoryModal = ref(false)

function getInitials(first: string, last: string): string {
  return `${first.charAt(0)}${last.charAt(0)}`.toUpperCase()
}

function fetchHistory() {
  historyLoading.value = true
  historyError.value = ''
  api
    .getAppointmentHistory(props.patient.id, auth.token)
    .then((data) => { history.value = data; historyError.value = '' })
    .catch((err: Error) => { history.value = []; historyError.value = err.message })
    .finally(() => { historyLoading.value = false })
}

watch(showHistoryModal, (open) => { if (open) fetchHistory() })

const cancellingAppt = computed(() => props.upcomingAppointments.find((a) => a.id === pendingCancelId.value) ?? null)

async function confirmCancel(reason?: string) {
  if (!pendingCancelId.value) return
  const id = pendingCancelId.value
  pendingCancelId.value = null
  isCancelling.value = true
  cancellingId.value = id
  try {
    emit('cancelAppointment', id, reason)
  } finally {
    cancellingId.value = null
    isCancelling.value = false
  }
}

async function handleMarkAttendance(appointmentId: string, attended: boolean) {
  await api.markAttendance(appointmentId, { attended }, auth.token)
  history.value = history.value.map((h) => (h.id === appointmentId ? { ...h, attended } : h))
}

const soonest = computed(() => (props.upcomingAppointments.length > 0 ? props.upcomingAppointments[0]! : null))
const restCount = computed(() => props.upcomingAppointments.length - 1)
const rebookDoctor = computed(() => soonest.value ?? props.lastDoctor)
</script>

<template>
  <motion.div :initial="{ opacity: 0, y: 12 }" :animate="{ opacity: 1, y: 0 }" :transition="{ duration: 0.3, ease: 'easeOut' }">
    <Card class="w-full mx-auto bg-transparent ring-0 shadow-none overflow-visible">
      <CardHeader class="px-0">
        <CardTitle class="text-xl text-foreground">Welcome back, {{ patient.first_name }}</CardTitle>
        <CardDescription>Great to see you again — here's your information</CardDescription>
      </CardHeader>
      <CardContent class="px-0 space-y-5">
        <Card class="overflow-hidden shadow-sm shadow-black/[0.03] border pt-0 relative">
          <div class="h-24 bg-gradient-to-br from-amber-50 via-rose-50/60 to-primary/5" />
          <div class="absolute top-3 right-3 z-10 flex items-center gap-2">
            <Button variant="outline" size="sm" @click="showEditModal = true">
              <HugeIcon :icon="Edit01Icon" :stroke-width="2" />
              Edit profile
            </Button>
            <Button variant="outline" size="sm" @click="showHistoryModal = true">History</Button>
          </div>
          <CardContent class="relative pb-0">
            <div class="flex flex-row items-start gap-5">
              <Avatar class="border-4 border-[#ffffff] shadow-lg -mt-12 size-20 sm:size-28">
                <AvatarFallback class="bg-slate-300 text-xl font-semibold text-slate-900">
                  {{ getInitials(patient.first_name, patient.last_name) }}
                </AvatarFallback>
              </Avatar>
              <div class="flex-1 pb-1 min-w-0">
                <div class="flex items-center gap-2">
                  <h3 class="text-lg font-semibold leading-tight">{{ patient.first_name }} {{ patient.last_name }}</h3>
                  <Badge variant="secondary" class="text-[10px] px-2 py-0.5">Returning</Badge>
                </div>
                <div class="space-y-0.5 pt-2 text-sm text-muted-foreground">
                  <div class="flex items-center gap-3">
                    <HugeIcon :icon="Mail01Icon" :stroke-width="2" class="size-4 shrink-0" />
                    <span class="truncate">{{ patient.email }}</span>
                  </div>
                  <div class="flex items-center gap-3">
                    <HugeIcon :icon="CallIcon" :stroke-width="2" class="size-4 shrink-0" />
                    <span>{{ patient.phone }}</span>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
          <template v-if="lastDoctor">
            <Separator />
            <CardContent class="pt-5 space-y-3">
              <div class="flex items-center gap-2">
                <HugeIcon :icon="Appointment01Icon" :stroke-width="2" class="size-4 text-primary shrink-0" />
                <span class="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Last visit</span>
              </div>
              <div class="flex items-center justify-between gap-3">
                <div class="space-y-0.5 min-w-0">
                  <p class="text-sm font-semibold text-foreground">Dr. {{ lastDoctor.doctor_name }}</p>
                  <div class="flex items-center gap-1.5 text-xs text-muted-foreground">
                    <HugeIcon :icon="Clock01Icon" :stroke-width="2" class="size-3.5 shrink-0" />
                    <span>{{ lastDoctor.last_appointment_date }} &middot; {{ lastDoctor.last_appointment_time?.slice(0, 5) }}</span>
                  </div>
                </div>
                <Badge variant="outline" class="text-[10px] font-normal shrink-0">{{ lastDoctor.specialization }}</Badge>
              </div>
            </CardContent>
          </template>
        </Card>

        <div class="mt-6">
          <div class="space-y-3">
            <div v-if="upcomingAppointments.length > 0" class="flex items-center justify-between gap-4 min-h-5 mt-2">
              <p class="text-xs font-semibold uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                <HugeIcon :icon="Time02Icon" :stroke-width="2" class="size-3.5 text-primary shrink-0" />
                Upcoming appointments
                <span class="text-[10px] font-medium text-primary bg-primary/10 px-1.5 py-0.5 rounded-full">{{ upcomingAppointments.length }}</span>
              </p>
              <button
                v-if="restCount > 0"
                type="button"
                class="text-xs font-medium text-primary underline-offset-2 hover:underline transition-colors shrink-0"
                @click="showAllModal = true"
              >
                View all ({{ upcomingAppointments.length }})
              </button>
            </div>

            <div v-if="upcomingLoading" class="flex items-center justify-center gap-2.5 py-5">
              <Spinner />
              <span class="text-xs text-muted-foreground">Loading appointments...</span>
            </div>
            <template v-else>
              <AppointmentCard
                v-if="soonest"
                :key="soonest.id"
                :appointment="soonest"
                :cancelling="cancellingId === soonest.id"
                @reschedule-time="emit('rescheduleTime', soonest)"
                @reschedule-doctor="emit('rescheduleDoctor', soonest)"
                @cancel="pendingCancelId = soonest.id"
              />

              <div v-if="upcomingError" class="flex flex-col items-center gap-4 rounded-xl bg-amber-50/70 border border-amber-200/50 py-10 px-6">
                <svg width="72" height="72" viewBox="0 0 72 72" fill="none" xmlns="http://www.w3.org/2000/svg" class="shrink-0">
                  <rect x="14" y="18" width="44" height="44" rx="6" class="fill-amber-200/70" stroke="#d97706" stroke-width="1.5" stroke-linejoin="round" />
                  <line x1="22" y1="30" x2="50" y2="30" class="stroke-amber-300" stroke-width="2" stroke-linecap="round" />
                  <line x1="22" y1="38" x2="44" y2="38" class="stroke-amber-300" stroke-width="2" stroke-linecap="round" />
                  <line x1="22" y1="46" x2="38" y2="46" class="stroke-amber-300" stroke-width="2" stroke-linecap="round" />
                  <circle cx="56" cy="18" r="10" class="fill-amber-100" stroke="#d97706" stroke-width="1.5" />
                  <path d="M56 14V18H60" class="stroke-amber-500" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                  <circle cx="56" cy="18" r="2" class="fill-amber-400" />
                </svg>
                <div class="text-center space-y-1">
                  <p class="text-sm font-semibold text-amber-800">Oops! Something went wrong</p>
                  <p class="text-xs text-amber-600/80 max-w-xs mx-auto">{{ upcomingError }}</p>
                </div>
                <button
                  type="button"
                  class="inline-flex items-center gap-1.5 text-xs font-medium text-amber-700 bg-amber-100/80 hover:bg-amber-200/60 rounded-lg px-4 py-2 transition-colors"
                  @click="emit('retryUpcoming')"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="shrink-0">
                    <path d="M21.5 2v6h-6M2.5 22v-6h6M2 11.5a10 10 0 0 1 18.8-4.3M22 12.5a10 10 0 0 1-18.8 4.2" />
                  </svg>
                  Try again
                </button>
              </div>
              <div v-else-if="upcomingAppointments.length === 0" class="flex flex-col items-center gap-2 rounded-xl bg-white border-2 border-dashed border-foreground/10 py-10 px-4">
                <HugeIcon :icon="Appointment01Icon" :stroke-width="2" class="size-6 text-muted-foreground/40 shrink-0" />
                <p class="text-xs text-muted-foreground">No upcoming appointments</p>
                <button
                  type="button"
                  class="text-xs font-medium text-primary underline-offset-2 hover:underline transition-colors mt-1"
                  @click="showHistoryModal = true"
                >
                  View past appointments
                </button>
              </div>
            </template>
          </div>
        </div>

        <div v-if="!upcomingLoading && upcomingAppointments.length >= 3" class="flex flex-col items-center gap-2 rounded-xl bg-amber-50 border border-amber-200/60 py-4 px-4 text-center">
          <p class="text-xs font-medium text-amber-800">
            You have {{ upcomingAppointments.length }} upcoming appointments — the maximum allowed.
          </p>
          <p class="text-[11px] text-amber-700/70">Please cancel or reschedule an existing appointment to book a new one.</p>
        </div>

        <div v-else-if="!upcomingLoading && upcomingAppointments.length < 3 && rebookDoctor" class="flex flex-col gap-3">
          <Button class="w-full h-11 text-base gap-2 shadow-xs" @click="emit('rebookWithLastDoctor', rebookDoctor.doctor_id, rebookDoctor.doctor_name)">
            Rebook with Dr. {{ rebookDoctor.doctor_name }}
            <HugeIcon :icon="ArrowRight02Icon" :stroke-width="2" class="size-4" />
          </Button>
          <Button variant="outline" class="w-full h-11 text-base bg-white" @click="emit('changeDoctor')">Choose a different doctor</Button>
        </div>

        <Button
          v-else-if="!upcomingLoading && upcomingAppointments.length === 0"
          class="w-full h-11 text-base gap-2 shadow-xs"
          @click="emit('changeDoctor')"
        >
          {{ doctorCount > 1 ? 'Book an appointment' : 'Continue' }}
          <HugeIcon :icon="ArrowRight02Icon" :stroke-width="2" class="size-4" />
        </Button>
      </CardContent>
    </Card>

    <UpcomingAppointmentsModal
      v-if="showAllModal"
      :appointments="upcomingAppointments"
      @close="showAllModal = false"
      @reschedule-time="(a) => emit('rescheduleTime', a)"
      @reschedule-doctor="(a) => emit('rescheduleDoctor', a)"
      @cancel-appointment="(id, reason) => emit('cancelAppointment', id, reason)"
    />

    <CancelAppointmentDialog
      :open="pendingCancelId !== null"
      @update:open="(v) => { if (!v) pendingCancelId = null }"
      :appointment="cancellingAppt"
      :is-cancelling="isCancelling"
      @confirm="confirmCancel"
    />

    <HistoryModal
      v-if="showHistoryModal"
      :history="history"
      :loading="historyLoading"
      :error="historyError"
      :on-retry="fetchHistory"
      :on-mark-attendance="handleMarkAttendance"
      @close="showHistoryModal = false"
    />

    <EditProfileModal
      v-if="showEditModal"
      :patient="patient"
      @close="showEditModal = false"
      @saved="(p) => emit('patientUpdated', p)"
    />
  </motion.div>
</template>
