// frontend-nuxt/app/components/ui/Button.vue
<script setup lang="ts">
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

// Base UI's polymorphic render/asChild plumbing from the React version is
// dropped in favor of a plain `as` prop — the one live call site that needs
// polymorphism (DropdownMenuTrigger wrapping a Button in AppointmentDetailModal)
// is handled by reka-ui's own as-child mechanism on the trigger, not by Button
// itself needing to merge props.
const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-md border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/80',
        outline:
          'border-border bg-background shadow-xs hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground',
        secondary:
          'bg-secondary text-secondary-foreground hover:bg-secondary/80 aria-expanded:bg-secondary aria-expanded:text-secondary-foreground',
        ghost: 'hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground',
        destructive:
          'bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default:
          'h-9 gap-1.5 px-2.5 in-data-[slot=button-group]:rounded-md has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2',
        xs: "h-6 gap-1 rounded-[min(var(--radius-md),8px)] px-2 text-xs in-data-[slot=button-group]:rounded-md has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-8 gap-1 rounded-[min(var(--radius-md),10px)] px-2.5 in-data-[slot=button-group]:rounded-md has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5",
        lg: 'h-10 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2',
        icon: 'size-9',
        'icon-xs':
          "size-6 rounded-[min(var(--radius-md),8px)] in-data-[slot=button-group]:rounded-md [&_svg:not([class*='size-'])]:size-3",
        'icon-sm': 'size-8 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-md',
        'icon-lg': 'size-10',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'default',
    },
  }
)

export type ButtonVariant = VariantProps<typeof buttonVariants>['variant']
export type ButtonSize = VariantProps<typeof buttonVariants>['size']

const props = withDefaults(
  defineProps<{
    class?: string
    variant?: ButtonVariant
    size?: ButtonSize
    as?: string
    type?: string
    disabled?: boolean
  }>(),
  { variant: 'default', size: 'default', as: 'button', type: 'button' }
)
</script>

<template>
  <component
    :is="props.as"
    data-slot="button"
    :type="props.as === 'button' ? props.type : undefined"
    :disabled="props.disabled"
    :class="cn(buttonVariants({ variant: props.variant, size: props.size }), props.class)"
  >
    <slot />
  </component>
</template>

// frontend-admin/src/components/Button.tsx
import { HugeiconsIcon } from '@hugeicons/react';
import { Loading02Icon } from '@hugeicons/core-free-icons';
import { cn } from '@/lib/utils';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  loading?: boolean;
  icon?: any;
  iconRight?: any;
}

const variants = {
  primary:
    'bg-emerald-600 text-white shadow-[0_1px_3px_rgba(5,150,105,0.2)] hover:bg-emerald-500 active:bg-emerald-700',
  secondary:
    'bg-card text-foreground border border-border shadow-[0_1px_2px_rgba(0,0,0,0.03)] hover:bg-muted hover:border-border active:bg-muted',
  ghost:
    'text-muted-foreground hover:bg-muted active:bg-muted',
  danger:
    'bg-red-600 text-white shadow-[0_1px_3px_rgba(220,38,38,0.2)] hover:bg-red-500 active:bg-red-700',
};

const sizes = {
  sm: 'h-8 px-4 text-xs gap-1.5 rounded-full',
  md: 'h-9 px-5 text-sm gap-2 rounded-full',
  lg: 'h-10 px-6 text-sm gap-2 rounded-full',
};

export function Button({
  variant = 'primary',
  size = 'md',
  loading = false,
  icon: Icon,
  iconRight: IconRight,
  children,
  className,
  disabled,
  ...props
}: ButtonProps) {
  return (
    <button
      className={cn(
        'inline-flex items-center justify-center font-medium transition-all duration-150',
        'disabled:opacity-50 disabled:pointer-events-none',
        'active:scale-[0.97]',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500/30 focus-visible:ring-offset-1',
        variants[variant],
        sizes[size],
        className
      )}
      disabled={disabled || loading}
      {...props}
    >
      {loading ? (
        <HugeiconsIcon icon={Loading02Icon} className="size-4 animate-spin" />
      ) : Icon ? (
        <HugeiconsIcon icon={Icon} className="size-4" />
      ) : null}
      {children}
      {IconRight && !loading && <HugeiconsIcon icon={IconRight} className="size-4" />}
    </button>
  );
}
