// frontend-nuxt/app/components/ui/InputOtp.vue
<script setup lang="ts">
// Ported onto vue-input-otp (vs React's input-otp behind the old ui/input-otp.tsx).
// Unlike the React version, vue-input-otp exposes slot state directly via the
// default slot's render props (no separate OTPInputContext + per-slot
// sub-components needed) — so this is one component instead of four
// (InputOTP/InputOTPGroup/InputOTPSlot/InputOTPSeparator), since AuthFlow is
// the only consumer and always renders a fixed 6-digit grouped layout.
import { OTPInput } from 'vue-input-otp'
import { MinusSignIcon } from '@hugeicons/core-free-icons'
import { cn } from '@/lib/utils'

const props = withDefaults(
  defineProps<{
    id?: string
    length?: number
    inputSize?: 'xl' | 'default'
    modelValue?: string
    autofocus?: boolean
    disabled?: boolean
  }>(),
  { length: 6, inputSize: 'default' }
)

const emit = defineEmits<{
  'update:modelValue': [value: string | undefined]
  complete: [value: string]
}>()

const slotClass = (size: 'xl' | 'default') =>
  cn(
    'relative flex items-center justify-center border-y border-r border-input shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md aria-invalid:border-destructive data-[active=true]:z-10 data-[active=true]:border-ring data-[active=true]:ring-3 data-[active=true]:ring-ring/50',
    size === 'xl' ? 'size-10 sm:size-12 text-base sm:text-lg' : 'size-9 text-sm'
  )
</script>

<template>
  <OTPInput
    :id="props.id"
    data-slot="input-otp"
    :data-size="props.inputSize"
    :maxlength="props.length"
    :model-value="props.modelValue"
    :autofocus="props.autofocus"
    :disabled="props.disabled"
    inputmode="numeric"
    spellcheck="false"
    :container-class="cn('cn-input-otp flex items-center has-disabled:opacity-50', props.inputSize === 'xl' && 'gap-2 sm:gap-5')"
    @update:model-value="(v) => emit('update:modelValue', v)"
    @complete="(v) => emit('complete', v)"
  >
    <template #default="{ slots }">
      <!-- Mobile: single ungrouped row -->
      <div class="flex items-center sm:hidden">
        <div
          v-for="(slot, i) in slots"
          :key="i"
          data-slot="input-otp-slot"
          :data-active="slot.isActive"
          :class="slotClass(props.inputSize)"
        >
          {{ slot.char }}
          <div v-if="slot.hasFakeCaret" class="pointer-events-none absolute inset-0 flex items-center justify-center">
            <div :class="cn('w-px animate-caret-blink bg-foreground duration-1000', props.inputSize === 'xl' ? 'h-6' : 'h-4')" />
          </div>
        </div>
      </div>
      <!-- sm+: grouped in pairs with separators -->
      <div class="hidden sm:flex items-center gap-0">
        <template v-for="group in 3" :key="group">
          <div class="flex items-center">
            <div
              v-for="i in [ (group - 1) * 2, (group - 1) * 2 + 1 ]"
              :key="i"
              data-slot="input-otp-slot"
              :data-active="slots[i]?.isActive"
              :class="slotClass(props.inputSize)"
            >
              {{ slots[i]?.char }}
              <div v-if="slots[i]?.hasFakeCaret" class="pointer-events-none absolute inset-0 flex items-center justify-center">
                <div :class="cn('w-px animate-caret-blink bg-foreground duration-1000', props.inputSize === 'xl' ? 'h-6' : 'h-4')" />
              </div>
            </div>
          </div>
          <div
            v-if="group < 3"
            data-slot="input-otp-separator"
            role="separator"
            :class="cn('flex items-center', props.inputSize === 'xl' && 'px-1')"
          >
            <HugeIcon :icon="MinusSignIcon" :stroke-width="2" :class="props.inputSize === 'xl' ? 'size-6' : 'size-4'" />
          </div>
        </template>
      </div>
    </template>
  </OTPInput>
</template>

// frontend/src/components/ui/input-otp.tsx
import * as React from "react"
import { createContext, useContext } from "react"
import { OTPInput, OTPInputContext } from "input-otp"

import { cn } from "@/lib/utils"
import { HugeiconsIcon } from "@hugeicons/react"
import { MinusSignIcon } from "@hugeicons/core-free-icons"

const OTPInputSizeContext = createContext<"default" | "xl">("default")

function InputOTP({
  className,
  containerClassName,
  inputSize,
  ...props
}: React.ComponentProps<typeof OTPInput> & {
  containerClassName?: string
  inputSize?: "xl"
}) {
  return (
    <OTPInputSizeContext.Provider value={inputSize ?? "default"}>
      <OTPInput
        data-slot="input-otp"
        data-size={inputSize ?? "default"}
        containerClassName={cn(
          "cn-input-otp flex items-center has-disabled:opacity-50",
          inputSize === "xl" && "gap-2 sm:gap-5",
          containerClassName
        )}
        spellCheck={false}
        className={cn("disabled:cursor-not-allowed", inputSize === "xl" && "gap-2 sm:gap-5", className)}
        {...props}
      />
    </OTPInputSizeContext.Provider>
  )
}

function InputOTPGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="input-otp-group"
      className={cn(
        "flex items-center has-aria-invalid:border-destructive has-aria-invalid:ring-3 has-aria-invalid:ring-destructive/20 dark:has-aria-invalid:ring-destructive/40",
        className
      )}
      {...props}
    />
  )
}

function InputOTPSlot({
  index,
  className,
  ...props
}: React.ComponentProps<"div"> & {
  index: number
}) {
  const inputOTPContext = React.useContext(OTPInputContext)
  const size = useContext(OTPInputSizeContext)
  const { char, hasFakeCaret, isActive } = inputOTPContext?.slots[index] ?? {}

  return (
    <div
      data-slot="input-otp-slot"
      data-active={isActive}
      className={cn(
        "relative flex items-center justify-center border-y border-r border-input shadow-xs transition-all outline-none first:rounded-l-md first:border-l last:rounded-r-md aria-invalid:border-destructive data-[active=true]:z-10 data-[active=true]:border-ring data-[active=true]:ring-3 data-[active=true]:ring-ring/50 data-[active=true]:aria-invalid:border-destructive data-[active=true]:aria-invalid:ring-destructive/20 dark:bg-input/30 dark:data-[active=true]:aria-invalid:ring-destructive/40",
        size === "xl" ? "size-10 sm:size-12 text-base sm:text-lg" : "size-9 text-sm",
        className
      )}
      {...props}
    >
      {char}
      {hasFakeCaret && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div className={cn("w-px animate-caret-blink bg-foreground duration-1000", size === "xl" ? "h-6" : "h-4")} />
        </div>
      )}
    </div>
  )
}

function InputOTPSeparator({ className, ...props }: React.ComponentProps<"div">) {
  const size = useContext(OTPInputSizeContext)
  return (
    <div
      data-slot="input-otp-separator"
      role="separator"
      className={cn(
        "flex items-center [&_svg:not([class*='size-'])]:size-4",
        size === "xl" && "[&_svg:not([class*='size-'])]:size-6 px-1",
        className
      )}
      {...props}
    >
      <HugeiconsIcon icon={MinusSignIcon} strokeWidth={2} />
    </div>
  )
}

export { InputOTP, InputOTPGroup, InputOTPSlot, InputOTPSeparator }
